<!DOCTYPE html>
<html lang="en-AU">
<head>
	<title>Float Terms &amp; Conditions | Important Terms At Float The Flop</title>
	<meta content="Please read this important documentation regarding the Float The Flop Terms and Consitions, it's there to protect you and to make sure everything is clear to you." name="description">
	<?php include "includes/section_head.php";?>
</head>
<body class="header-scroll-reveal overflow-x-hidden">
	<div id="wrapper" class="overflow-x-hidden">
		<?php include "includes/section_menu.php";?>
			<div id="middle">
				<section class="bg-dark">
					<svg class="position-absolute top-0 start-0 end-0" viewBox="39.062 480.469 1000 39.062">
						<polygon fill="#fff" points="0,519.531 0,480.469 1000,480.469 "></polygon>
					</svg>
					<div class="absolute-full w-100 overflow-hidden opacity-9"><img alt="..." class="img-fluid" height="2000" src="../assets/images/masks/shape-line-lense.svg" width="2000"></div>
					<div class="container d-middle">
						<div class="pt-6 text-white text-center" data-aos="flip-down" data-aos-duration="0" data-aos-delay="0">
							<h1 class="h2-xs mb-1">Terms &amp; Conditions</h1>
							<p class="lead mb-5">Important Documentation</p>
						</div>
					</div>
				</section>
				<section>
					<div class="container">
						<div class="article-format">
							<h2>Overview</h2>
							<p>This website is owned and operated by <span class="terms_company_name">Float The Flop</span>. Throughout the site, the terms "we", "us", "our" and "Float" refer to <span class="terms_company_name">Float The Flop</span>. <span class="terms_company_name">Float The Flop</span> offers online poker products and services including this website, poker game-play through the use of 3rd party services and poker apps and various tools available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, privacy policy, risk disclosures and legal documents stated here.</p>
							<p>By visiting our site and the continued use of it, you engage in our "Service" and agree to be bound by the following Terms and Conditions, including those additional Terms and Conditions and policies referenced herein and/or available by hyperlink. These Terms and Conditions apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content.</p>
							<p>Please read these Terms and Conditions carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms and Conditions. If you do not agree to all the Terms and Conditions of this agreement, then you may not access the website or use any services. If these Terms and Conditions are considered an offer, acceptance is expressly limited to these Terms and Conditions.</p>
							<p>Any new features or tools which are added to what we offer shall also be subject to the Terms and Conditions. You can review the most current version of the Terms and Conditions at any time on this page. We reserve the right to update, change or replace any part of these Terms and Conditions by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.</p>
							<p>By agreeing to these Terms and Conditions, you are stating that you are over the age of 21, or that you are the age of majority in your state or province of residence.</p>
							<p>You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</p>
							<p>You must not transmit any worms or viruses or any code of a destructive nature.</p>
							<p>A breach or violation of any of the Terms will result in an immediate termination of your Services.</p>
							<h2>General conditions</h2>
							<p>We reserve the right to refuse service to anyone for any reason at any time.</p>
							<p>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</p>
							<p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us.</p>
							<p>The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
							<h2>Accuracy, completeness and timeliness of information</h2>
							<p>We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own risk.</p>
							<p>This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site.</p>
							<h2>Modifications to the service and prices</h2>
							<p>Prices for our products are subject to change without notice.</p>
							<p>We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.</p>
							<p>We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.</p>
							<h2>Products or services (if applicable)</h2>
							<p>Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange only according to our Return Policy.</p>
							<p>We have made every effort to display as accurately as possible the colors and images of our products that appear at the store. We cannot guarantee that your computer monitor's display of any color will be accurate.</p>
							<p>We reserve the right but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at any time without notice, at the sole discretion of us. We reserve the right to discontinue any product or service at any time. Any offer for any product or service made on this site is void where prohibited.</p>
							<p>We do not warrant that the quality of any products, services, information, or other material available from us or obtained by you will meet your expectations, or that any errors in the products or service will be corrected.</p>
							<h2>Accuracy of billing and account information</h2>
							<p>We reserve the right to refuse any services to you. We may, in our sole discretion, limit or cancel existing services to you at our sole discretion. If we make a change to or cancel a purchase, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors.</p>
							<p>You agree to provide current, complete and accurate purchase and account information for all purchases made through our website. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates so that we can complete your transactions and contact you as needed.</p>
							<h2>Software modifications</h2>
							<p>Users may not attempt to modify, decompile, reverse-engineer or disassemble the Software we offer including this website, any 3rd party software such as the the poker app that we run our games on, in any way.</p>
							<h2>Personal use</h2>
							<p>The Service is intended solely for the User's personal use. The User is only allowed to use our services for his/her personal entertainment. The User must provide full and truthful information in respect of all details and information provided by the User to Flot the Flop and the User is obligated to update such details in the event of any change thereto.</p>
							<h2>Anti-money laundering</h2>
							<p>In compliance with anti-money laundering legislation, Users need to be aware they may be required to produce personal documentation (such as Government issued ID, bank statements and utility bills) upon request in order for their purchases to be processed. This allows Float The Flop to help protect the Users and prevent Float The Flop being used as a vehicle for money laundering or fraud.</p>
							<h2>Transactions</h2>
							<p>Float The Flop reserves the right to decline any account transaction requests or to overturn any account transaction upon suspicion of breach of any of the terms of this Agreement by the user.
							A sending User agrees that they may only make an account transfer to enable a receiving User to play the Poker Games and not for any other purpose.
							A receiving User agrees that they may only use the funds from an account transfer to play the Poker Games and not for any other purpose.</p>
							<p>Users cannot withdraw funds directly received from a transfer; winnings arising from playing the Games using the transferred funds that subsequently contribute to a withdrawal request will be reviewed in accordance with Floats' internal controls, policies and procedures. The User agrees to and accepts the terms and conditions relating to chip transaction processing and currency exchange located here.</p>
							<h2>Hand history</h2>
							<p>By using our service, you agree to allow Float The Flop full access to view your hand history played through the poker apps that we run our games on or any other platform we use to host the Float The Flop club. You authorize us to request and obtain your hand history from third-party services that are directly related to your game-play through the Float The Flop club.</p>
							<p>You authorize your hand history to be used internally by the Float The Flop security team, its staff, management and third-party security services for analyses for collusion, fraud and cheating detection. 
							<p>You understand that we apply quantitative algorithms to your hand history and the hand history from all players to automatically flag suspicious activity for further analysis.</p>
							<p>You authorise your hand history to be stored indefinitely on our secure and private servers for its intended use.</p>
							<p>You acknowledge that under no circumstance, other than what is stated in our Terms and Conditions and Privacy Policy, will your hand history be provided to you or any third parties unless in compliance with the law or court order.</p>
							<p>By using our service, you agree to allow Float The Flop to use your hand history as a legal defence against you or other players without any further authorisation. You understand that we are under no obligation to delete your hand history upon request from you or any third-party.</p>
							<h2>Collusion</h2>
							<p>Collusion between Users by sharing poker hole cards or by any other methods is strictly forbidden. Float The Flop reserves the right, in addition to other measures, to restrict seating and/or to prohibit Users from playing at a particular poker table or in a tournament, including restricting two or more Users from playing together at the same table or in the same tournament. Also, Float The Flop reserves the right to consider any collusion or attempt at collusion between players (including Users) as a material breach of this Agreement and accordingly Float The Flop shall have the right to terminate a User's account if a User engages or attempts to engage in any such activity, regardless of the outcome of such attempt.</p>
							<h2>Player assistance software</h2>
							<p>Float The Flop prohibits external player assistance software ("PAS") that are designed to provide an "unfair advantage" to players. Float The Flop defines "PAS" as computer software (other than the platform we host our games on), and non-software-based systems (e.g. web sites, subscription services and physical materials). We do not allow Platform Overlays or HUDS to be used as a player assistance tool. For the avoidance of doubt, what is prohibited encompasses but is not limited to accessing or compiling information on other players beyond that which the User has personally observed through the User's own game-play or receiving advice, direction or assistance on how to play, in real-time, that goes beyond a basic level.</p>
							<h2>Poker bots (BOTS)</h2>
							<p>The use of artificial intelligence including, without limitation, poker bots are strictly forbidden in connection with the poker platform we host our games on and the service Float The Flop offers. All actions taken concerning a users game-play must be executed personally by players through the user interface accessible by use of the Software, and without the assistance of any form of artificial intelligence.</p>
							<p>You agree that Float The Flop may take steps to detect and prevent the use of prohibited PAS. These steps may include, but are not limited to, examination of software programs running concurrently with Float The Flop platform or poker app on the User's computer. You agree that you will not attempt to bypass, interfere with, or block such steps, including, without limitation, the use of third party software that bypasses, interferes with, or blocks such steps.</p>
							<h2>Fraud</h2>
							<p>If Float The Flop deems that a User has engaged or attempted to engage in fraudulent, unlawful, dishonest or improper activity while using the Service, including without limitation, engaging in any of the activities set forth in these Terms and Conditions or any other game manipulation, or the making of any fraudulent payment, including without limitation, use of a stolen credit card or fraudulent chargeback or money laundering, Float The Flop shall be entitled to take such action as it sees fit.</p>
							<h2>Chip dumping</h2>
							<p>Chip-dumping occurs when any User intentionally loses a poker hand in order to deliberately transfer his chips to another User. Any User who participates or attempts to participate in chip-dumping with any other User, including being the recipient of funds, while using the Service may be permanently banned from using the Float service and their Account may be terminated immediately. In such circumstances Float The Flop will be under no obligation to refund to you any monies that may be in your Account at such time.</p>
							<h2>Optional tools</h2>
							<p>We may provide you with access to third-party tools over which some parts we neither monitor nor have any control nor input such as the poker platform or app that we host our games on.</p>
							<p>You acknowledge and agree that we provide access to such tools "as is" and "as available" without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools.</p>
							<p>Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).</p>
							<p>We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms and Conditions.</p>
							<h2>Third-Party links</h2>
							<p>Certain content, products and services available via our Service may include materials from third-parties.</p>
							<p>Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.</p>
							<p>We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</p>
							<h2>User comments, feedback and other submissions</h2>
							<p>If at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.</p>
							<p>We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms and Conditions.</p>
							<p>You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libellous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.</p>
							<h2>Personal information</h2>
							<p>Your submission of personal information through the store is governed by our Privacy Policy located on this website.</p>
							<h2>Errors, inaccuracies and omissions</h2>
							<p>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order).</p>
							<p>We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.</p>
							<h2>Prohibited uses</h2>
							<p>In addition to other prohibitions as set forth in the Terms and Conditions, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
							<h2>Disclaimer of warranties; limitation of liability</h2>
							<p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.</p>
							<p>We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</p>
							<p>You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.</p>
							<p>You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
							<p>In no case shall <span class="terms_company_name">Float The Flop</span>, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
							<h2>Indemnification</h2>
							<p>You agree to indemnify, defend and hold harmless <span class="terms_company_name">Float The Flop</span> and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third-party due to or arising out of your breach of these Terms and Conditions or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>
							<h2>Severability</h2>
							<p>In the event that any provision of these Terms and Conditions is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms and Conditions, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
							<h2>Termination</h2>
							<p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.</p>
							<p>These Terms and Conditions are effective unless and until terminated by either you or us. You may terminate these Terms and Conditions at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.</p>
							<p>If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms and Conditions, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p>
							<h2>Entire agreement</h2>
							<p>The failure of us to exercise or enforce any right or provision of these Terms and Conditions shall not constitute a waiver of such right or provision.</p>
							<p>These Terms and Conditions and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms and Conditions).</p>
							<p>Any ambiguities in the interpretation of these Terms and Conditions shall not be construed against the drafting party.</p>
							<h2>Governing law</h2>
							<p>These Terms and Conditions and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of <span class="terms_company_address">- Company Address -</span>.</p>
							<h2>Changes to our Terms and Conditions</h2>
							<p>You can review the most current version of the Terms and Conditions at any time at this page.</p>
							<p>We reserve the right, at our sole discretion, to update, change or replace any part of these Terms and Conditions by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms and Conditions constitutes acceptance of those changes.</p>
							<h2>Contact information</h2>
							<p>Questions about the Terms and Conditions should be sent to us at <span class="terms_company_email">support@float-the-flop.com</span>.</p>
							<p>Last Update: <span class="terms_update_date">1st September, 2020</span></p>
						</div>
					</div>
				</section>
			</div>
			<?php include "includes/section_footer.php";?>
	</div>
</body>
</html>