<section class="clearfix bg-dark">
	<div class="col-12 col-lg-6 float-left">
		<div class="mb--15 position-relative bg-gradient-pink text-white p-5 shadow-pink-xs rounded text-center" data-aos="zoom-in-left" data-aos-delay="0" data-aos-offset="0"> <span class="badge badge-blue fs--45 w--100 h--100 badge-pill rounded-circle border bw--3"><i class="fi fi-users mt-1"></i></span>
			<h3 class="fs--20 mt--60">Your Instant Personalised Players Portal</h3>
			<p class="px-5 p-0-xs">As soon as you register, you instantly become an anonomous poker agent, allowing you to easily and safely refer your network of poker friends to Float The Flop, and generate an income from their gameplay.</p>
			<div class="absolute-full w-100 overflow-hidden opacity-9"><img alt="..." class="img-fluid" height="2000" src="../assets/images/masks/shape-line-lense.svg" width="2000"></div>
		</div>
	</div>
	<div class="col-12 col-lg-6 float-right">
		<div class=" mb--15 position-relative bg-gradient-pink text-white p-5 shadow-pink-xs rounded text-center" data-aos="zoom-in-right" data-aos-delay="0" data-aos-offset="0"> <span class="badge badge-blue fs--45 w--100 h--100 badge-pill rounded-circle border bw--3"><i class="fi fi-mollecules mt-1"></i></span>
			<h3 class="fs--20 mt--60">We Invite Your Friends on Your Behalf</h3>
			<p class="px-5 p-0-xs">You receive your own personalised players portal, as soon as you register. In your players portal are detailed reports of the bonuses you receive from your gameplay, and bonuses generated by your referred.</p>
			<div class="absolute-full w-100 overflow-hidden opacity-9"><img alt="..." class="img-fluid" height="2000" src="../assets/images/masks/shape-line-lense.svg" width="2000"></div>
		</div>
	</div>
</section> 
<section class="bg-gradient-pink-2 shadow-pink-xs rounded mt--n30">
	<div class="absolute-full w-100 overflow-hidden opacity-9"><img alt="..." class="img-fluid" height="2000" src="../assets/images/masks/shape-line-lense.svg" width="2000"></div>
	<div class="container">
		<h2 class="text-white text-center mt-4 pb-4" data-aos="zoom-out-up" data-aos-delay="0" data-aos-offset="0">Everyone's an Instant Poker Agent</h2>
		<div class="text-white text-center">
			<div class="mx-auto max-w-800">
				<h5 class="pb-1" data-aos="zoom-in-left" data-aos-delay="0" data-aos-offset="0">All the tools you need to become the ultimate poker agent</h5>
					<p data-aos="zoom-in-right" data-aos-delay="0" data-aos-offset="0">On your behalf, we send anonymous email campaigns and SMS campaigns to your poker friends. Everything you need to build your own poker business and earn an income is provided, just register and start adding your friends.</p>
			</div>
			<div class="col-12" data-aos="zoom-out-down" data-aos-delay="0" data-aos-offset="0"><img alt="..." class="lazyload rounded-xl img-fluid" data-src="assets/images/float-the-flop-marketing.svg" width="1170" height="780" defer ></div>
		</div>
	</div>
</section>